/**
 * 形状データの入出力フォーマット(作業計画 1F-3 の一部を先行実装)。
 * - 点群: PLY(binary_little_endian)
 * - サーフェス: STL(binary)
 * - アプリ内部保存用のメッシュバイナリ(ヘッダ+頂点+インデックス)
 */

/** 点群 → PLY (binary little endian) */
export function plyFromPoints(points: Float32Array): Blob {
  const count = Math.floor(points.length / 3);
  const header =
    'ply\n' +
    'format binary_little_endian 1.0\n' +
    'comment generated by scan2fem\n' +
    `element vertex ${count}\n` +
    'property float x\nproperty float y\nproperty float z\n' +
    'end_header\n';
  // 環境のエンディアンに関わらずリトルエンディアンで書き出す
  const buf = new ArrayBuffer(count * 12);
  const dv = new DataView(buf);
  for (let i = 0; i < count * 3; i++) dv.setFloat32(i * 4, points[i], true);
  return new Blob([header, buf], { type: 'application/octet-stream' });
}

/** 三角形メッシュ → STL (binary) */
export function stlFromMesh(positions: Float32Array, indices: Uint32Array): Blob {
  const triCount = Math.floor(indices.length / 3);
  const buf = new ArrayBuffer(84 + triCount * 50);
  const dv = new DataView(buf);
  const headerText = 'scan2fem surface export';
  for (let i = 0; i < Math.min(80, headerText.length); i++) {
    dv.setUint8(i, headerText.charCodeAt(i));
  }
  dv.setUint32(80, triCount, true);
  let off = 84;
  for (let t = 0; t < triCount; t++) {
    const a = indices[t * 3] * 3;
    const b = indices[t * 3 + 1] * 3;
    const c = indices[t * 3 + 2] * 3;
    const ux = positions[b] - positions[a];
    const uy = positions[b + 1] - positions[a + 1];
    const uz = positions[b + 2] - positions[a + 2];
    const vx = positions[c] - positions[a];
    const vy = positions[c + 1] - positions[a + 1];
    const vz = positions[c + 2] - positions[a + 2];
    let nx = uy * vz - uz * vy;
    let ny = uz * vx - ux * vz;
    let nz = ux * vy - uy * vx;
    const len = Math.hypot(nx, ny, nz) || 1;
    nx /= len;
    ny /= len;
    nz /= len;
    dv.setFloat32(off, nx, true);
    dv.setFloat32(off + 4, ny, true);
    dv.setFloat32(off + 8, nz, true);
    const verts = [a, b, c];
    for (let v = 0; v < 3; v++) {
      const p = verts[v];
      dv.setFloat32(off + 12 + v * 12, positions[p], true);
      dv.setFloat32(off + 16 + v * 12, positions[p + 1], true);
      dv.setFloat32(off + 20 + v * 12, positions[p + 2], true);
    }
    dv.setUint16(off + 48, 0, true);
    off += 50;
  }
  return new Blob([buf], { type: 'model/stl' });
}

/** アプリ内部保存用メッシュバイナリ: [uint32 vCount][uint32 iCount][f32 xyz...][u32 idx...] */
export function encodeMeshBinary(positions: Float32Array, indices: Uint32Array): ArrayBuffer {
  const buf = new ArrayBuffer(8 + positions.byteLength + indices.byteLength);
  const head = new Uint32Array(buf, 0, 2);
  head[0] = Math.floor(positions.length / 3);
  head[1] = indices.length;
  new Float32Array(buf, 8, positions.length).set(positions);
  new Uint32Array(buf, 8 + positions.byteLength, indices.length).set(indices);
  return buf;
}

export function decodeMeshBinary(buf: ArrayBuffer): {
  positions: Float32Array;
  indices: Uint32Array;
} {
  const head = new Uint32Array(buf, 0, 2);
  const vCount = head[0];
  const iCount = head[1];
  const positions = new Float32Array(buf, 8, vCount * 3);
  const indices = new Uint32Array(buf, 8 + vCount * 12, iCount);
  return { positions, indices };
}
